# Generated by Django 3.2.6 on 2022-10-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0002_alter_libro_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='edicion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
