# Generated by Django 3.2.6 on 2022-10-27 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0003_libro_edicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='materia',
        ),
    ]
