# Generated by Django 3.2.6 on 2022-10-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0004_remove_libro_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='materia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
